package gos

const MIDDLEWARE_DEFAULT_HTTP_MAX_IDLE_CONN = 100

const MIDDLEWARE_DEFAULT_HTTP_MAX_CONN_PER_HOST = 100

const MIDDLEWARE_DEFAULT_HTTP_MAX_IDLE_CONN_PER_HOST = 100

const MIDDLEWARE_DEFAULT_HTTP_TIMEOUT_MS = 10000
