name: Sync to Gitea

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  sync:
    name: Sync to Gitea
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Gitea
        env:
          SOURCE_REPO: "https://${{ github.repository_owner }}:${{ github.token }}@github.com/${{ github.repository }}.git"
          DESTINATION_REPO: ${{ secrets.GITEA_REMOTE_URL }}
        uses: wei/git-sync@v3
        with:
          source_repo: ${{ env.SOURCE_REPO }}
          source_branch: "main"
          destination_repo: ${{ env.DESTINATION_REPO }}
          destination_branch: "main"
